version: '3'
services:
  ladder:
    image: ghcr.io/kubero-dev/ladder:latest
    container_name: ladder
    build: .
    #restart: always
    #command: tail -f /dev/null
    #command: sh -c ./ladder
    environment:
      - PORT=8080
      - PREFORK=true
      #- GODEBUG=netdns=go+4
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M