name: Build Tailwind CSS

on:
  push:
    paths:
      - "handlers/form.html"
  workflow_dispatch:

jobs:
  tailwindbuilder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      -
        name: Build Tailwind CSS
        run: pnpm build
      -
        name: Commit generated stylesheet
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          else
            echo "Changes detected, committing..."
            git config --global user.name "Github action"
            git config --global user.email "username@users.noreply.github.com"
            git add cmd
            git commit -m "Generated stylesheet"
            git push
          fi